---

# Application settings.
project_path: "/home/{{ project_name }}"
application_path: "{{ project_path }}/www/{{ project_name }}"
virtualenv_path: "{{ project_path }}/www/venv"

project_log_dir: "{{ project_path }}/logs"
project_conf_dir: "{{ project_path }}/conf"
application_log_file: "{{ project_log_dir }}/{{ project_name }}.log"
requirements_file: "{{ application_path }}/requirements.txt"
requirements_extra: "{{ application_path }}/requirements.extra"

vassals_path: "/etc/uwsgi/vassals"

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ project_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ project_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"


# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"
